### ISSUE TITLE
The exporter panics when it looses connection to the Big-IP

### ISSUE THREAD

**Issue by cldmnky** [ExpressenAB/bigip_exporter#1]
We had an network outage, where the communication to the Big-IP was lost. The exporter paniced and exited, thus no more metrics.

**Comment by cgunning** [comment]
I've located the issue and a new release containing the fix as well as some other improvements should be available in the coming days

**Comment by cldmnky** [comment]
Good job! Looking forward to the new release!

Thanks!

**Comment by cgunning** [comment]
This is fixed in the new release 0.2.1
