### ISSUE TITLE
Dockerfile in Repo != Docker Image in Docker Hub

### ISSUE THREAD

**Issue by Smuggla** [ExpressenAB/bigip_exporter#13]
Could that be updated?

Thanks for all your work!

**Comment by cgunning** [comment]
Hi!

Thanks for your feedback. I've been bad at creating a release for the most recent changes due to a lot going on at work but I'll try to fix that as soon as possible! :)

**Comment by cgunning** [comment]
Hi,

I'm sorry that this has been taking so long but I've had a lot to do at work. I've released version 1.0.0 now and uploaded an image to Docker Hub as well. Let me know if you experience any issues.

Best regards,
Christoffer Gunning
