### ISSUE TITLE
Option to provide the bigip host (target) in a URL param

### ISSUE THREAD

**Issue by dannyk81** [ExpressenAB/bigip_exporter#22]
Thanks for this work!

I wonder if the exporter could be extended to support receiving the BigIP host (address) via a URL param from Prometheus.

This way, we don't need to deploy multiple exporter instances per each BigIP device and can control the targets to be scraped from Prometheus itself.

**Comment by klippo** [comment]
Check https://github.com/jenningsloy318/bigip_exporter

**Comment by dannyk81** [comment]
Thanks @klippo, we ended up using snmp-exporter to collect metrics from F5 and works really well for us, so I'm going to close this now.
