### ISSUE TITLE
undefined: prometheus.Handler

### ISSUE THREAD

**Issue by pmawan** [ExpressenAB/bigip_exporter#32]
hi - when i run the get command - 

go get github.com/ExpressenAB/bigip_exporter

i get this error - how can i fix this ?
/root/go/pkg/mod/github.com/!expressen!a!b/bigip_exporter@v0.0.0-20180222153255-e0f009c578b6/bigip_exporter.go:20:26: undefined: prometheus.Handler

thanks 
M.

**Comment by kgaughan** [comment]
Try using my branch on #27 - it fixes this issue.
